# Copyright (C) 2024-2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
---
- name: Deploy GenAI Gateway
  hosts: kube_control_plane
  vars:
    ansible_python_interpreter: /usr/bin/python3
    helm_charts_base_genai: "{{ lookup('env', 'PWD') }}/helm-charts/genai-gateway"
    helm_charts_base_genai_trace: "{{ lookup('env', 'PWD') }}/helm-charts/genai-gateway-trace"
    remote_helm_charts_base: "/tmp/helm-charts"    
  vars_files:
        - "{{ lookup('env', 'PWD') }}/scripts/vault.yml"
  gather_facts: false
  any_errors_fatal: "{{ any_errors_fatal | default(true) }}"
  environment: "{{ proxy_disable_env | default(env_proxy | default({})) }}"
  tasks:
    - name: Ensure Python pip module is installed
      ansible.builtin.package:
        name: python3-pip
        state: present
      become: true
    - name: Install Kubernetes Python SDK
      ansible.builtin.pip:
        name: kubernetes
        state: present
        executable: /usr/bin/pip3
      become: true
    - name: Install Deployment Client
      ansible.builtin.shell: |
        curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
      args:
        executable: /bin/bash
      become: true
    - name: Output config
      debug:
        var: cert_file, key_file, secret_name     
    - name: Create Namespace for GenAI Gateway
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Namespace
          metadata:
            name: genai-gateway          
    - name: Create TLS secret for GenAI Gateway
      community.kubernetes.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Secret
          metadata:
            name: "{{ secret_name }}"
            namespace: genai-gateway
          type: kubernetes.io/tls
          data:
            tls.crt: "{{ lookup('file', cert_file) | b64encode }}"
            tls.key: "{{ lookup('file', key_file) | b64encode }}"
      register: kubectl_output
    - name: TLS Create 
      debug:
        msg: "Secret {{ secret_name }} created."            
    - name: Copy Dependency Files Message
      debug:
        msg: "Copying dependency files to the nodes please wait..."    
    - name: Ensure Remote Directory Exists
      ansible.builtin.file:
        path: "{{ remote_helm_charts_base }}"
        state: directory
        mode: '0755'
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"    
    - name: Sync dependency files to Deployment Nodes
      ansible.posix.synchronize:
        src: "{{ item.src }}/"
        dest: "{{ item.dest }}/"
        recursive: yes
        delete: no
        mode: push
      loop:
        - { src: "{{ helm_charts_base_genai }}", dest: "{{ remote_helm_charts_base }}/genai-gateway" }
        - { src: "{{ helm_charts_base_genai_trace }}", dest: "{{ remote_helm_charts_base }}/genai-gateway-trace" }
                                            
    - name: Install GenAI Gateway System
      command: >
        helm upgrade --install genai-gateway {{ remote_helm_charts_base }}/genai-gateway
        --namespace genai-gateway
        --create-namespace
        --set env.LITELLM_MASTER_KEY={{ litellm_master_key }}
        --set env.LITELLM_SALT_KEY={{ litellm_salt_key }}
        --set env.REDIS_PASSWORD={{ redis_password }}
        --set env.LANGFUSE_SECRET_KEY={{ langfuse_secret_key }}
        --set env.LANGFUSE_PUBLIC_KEY={{ langfuse_public_key }}
        --set env.DATABASE_URL={{ database_url }}
        --set postgresql.auth.username={{ postgresql_username }}
        --set postgresql.auth.password={{ postgresql_password }}
        --set postgresql.auth.postgresPassword={{ postgresql_password }}
        --set redis.auth.password={{ redis_auth_password }}
        --set backup.s3.accessKeyId={{ aws_access_key }}
        --set backup.s3.secretAccessKey={{ aws_secret_key }}
        --set ingress.host={{ secret_name }}
        --set ingress.secretname={{ secret_name }}  
        -f {{ remote_helm_charts_base }}/genai-gateway/values.yaml  

    - name: Install GenAI Gateway Trace System
      command: >
        helm upgrade --install genai-gateway-trace {{ remote_helm_charts_base }}/genai-gateway-trace/charts/langfuse
        --namespace genai-gateway
        --set clickhouse.auth.username={{ clickhouse_username }} \
        --set clickhouse.auth.password={{ clickhouse_password }} \
        --set langfuse.additionalEnv[0].value={{ clickhouse_redis_url }} \
        --set langfuse.additionalEnv[3].value={{ clickhouse_username }} \
        --set langfuse.additionalEnv[4].value={{ clickhouse_password }} \
        --set langfuse.additionalEnv[9].value={{ langfuse_public_key }} \
        --set langfuse.additionalEnv[10].value={{ langfuse_secret_key }} \
        --set langfuse.additionalEnv[11].value={{ langfuse_login }} \
        --set langfuse.additionalEnv[12].value={{ langfuse_user }} \
        --set langfuse.additionalEnv[13].value={{ langfuse_password }} \
        --set langfuse.additionalEnv[18].value={{ minio_secret }} \
        --set langfuse.nextauth.secret={{ clickhouse_password }} \
        --set langfuse.salt={{ clickhouse_password }} \        
        --set minio.auth.rootPassword={{ minio_secret }} \
        --set minio.auth.rootUser={{ minio_user }} \
        --set postgresql.auth.password={{ postgres_password }} \
        --set postgresql.auth.username={{ postgres_user }} \
        --set valkey.auth.password={{ clickhouse_password }} \
        --set ingress.host="trace.{{ secret_name }}" \
        --set ingress.secretname="trace.{{ secret_name }}" \
        --set langfuse.nextauth.url="https://trace.{{ secret_name }}" \
        -f {{ remote_helm_charts_base }}/genai-gateway-trace/charts/langfuse/values.yaml