{{- if .Values.svcmonitor.enabled }}
# Copyright (C) 2024 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "vllm.fullname" . }}-service
  labels:
    release: {{ .Values.global.prometheusRelease }}
spec:
spec:
  namespaceSelector:
    matchNames:
    - default
  selector:
    matchLabels:
      app.kubernetes.io/instance: {{ include "vllm.fullname" . }}
  endpoints:
  - port: "vllm"
{{- end }}
