# Source: kray/helm-charts/tgi-llama-8b-cpu/templates/service.yaml
# Copyright (C) 2024 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
kind: Service
metadata:
  name: tgi-llama-8b-cpu
  labels:
    helm.sh/chart: tgi-1.0.0
    app.kubernetes.io/name: tgillama-8b-cpu
    app.kubernetes.io/instance: tgillama-8b-cpu
    app.kubernetes.io/version: "2.1.0"
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 2080
      protocol: TCP
      name: tgi-llama-8b-cpu
  selector:
    app.kubernetes.io/name: tgillama-8b-cpu
    app.kubernetes.io/instance: tgillama-8b-cpu