---
- name: Deploy Habana AI Operator Namespace and Labels
  hosts: kube_control_plane
  vars:
    ansible_python_interpreter: /usr/bin/python3
  gather_facts: false
  any_errors_fatal: "{{ any_errors_fatal | default(true) }}"
  environment: "{{ proxy_disable_env | default({}) }}"
  tasks:
    - name: Ensure pip is installed
      ansible.builtin.package:
        name: python3-pip
        state: present
      become: true
    - name: Install kubernetes library using pip
      ansible.builtin.pip:
        name: kubernetes
        state: present
        executable: /usr/bin/pip3
      become: true
    - name: Ensure jq is installed
      ansible.builtin.package:
        name: jq
        state: present
      become: true
    - name: Create habana-ai-operator namespace
      community.kubernetes.k8s:
        state: present
        kind: Namespace
        name: habana-ai-operator  
    - name: Label namespace for pod security enforcement
      community.kubernetes.k8s:
        state: present
        kind: Namespace
        name: habana-ai-operator
        resource_definition:
          metadata:
            labels:
              pod-security.kubernetes.io/enforce: privileged
              pod-security.kubernetes.io/audit: privileged
              pod-security.kubernetes.io/warn: privileged
    - name: Install Helm
      ansible.builtin.shell: |
        curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
      args:
        executable: /bin/bash
      become: true        
    - name: Add gaudi-helm repository using Helm module
      community.kubernetes.helm_repository:
        name: gaudi-helm
        repo_url: https://vault.habana.ai/artifactory/api/helm/gaudi-helm
        state: present
    - name: Install habana-ai-operator chart using Helm module
      community.kubernetes.helm:
        name: habana-ai-operator
        chart_ref: gaudi-helm/habana-ai-operator
        release_namespace: habana-ai-operator
        chart_version: 1.18.0-524
        state: present     
    - name: wait for habana-ai-operator pods to be running
      pause:
        minutes: 5
      register: pause_result
    - name: Output the result
      debug:
        msg: "waiting for habana-ai-operator pods to be running"
    - name: Ensure all habana-ai-operator pods are running and ready
      shell: |
        kubectl get pods -n habana-ai-operator -o json | jq -r '
          .items[] |
          select(.status.phase != "Running" or (.status.containerStatuses[] | select(.ready != true))) |
          .metadata.name' | wc -l
      register: pod_status
      until: pod_status.stdout == "0" and pod_status.rc == 0
      retries: 160
      delay: 10
      failed_when: pod_status.rc != 0 and pod_status.stdout != "0"
    - name: Output the result
      debug:
        msg: "All habana-ai-operator pods are running and ready."

   