keycloakTokenRoute:
  host: ""
  path: /token
  serviceName: keycloak
  servicePort: 80
  rewritePath: /realms/master/protocol/openid-connect/token
# TLS configuration
tls:
  host: ""
  secretName: ""
  secretNamespace: default
ingress:
  host: ""
  serviceName: auth-apisix-gateway
  servicePort: 80
  secretName: ""