all:
  hosts:
    master:
      ansible_host: 10.240.0.4
      ansible_user: ubuntu
      ansible_ssh_private_key_file:
  children:
    kube_control_plane:
      hosts:
        master:
    kube_node:
      hosts:
        master:
        master:
    etcd:
      hosts:
        master:
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
    calico_rr:
      hosts: {}
      
