---
# Copyright (C) 2024 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
kind: Service
metadata:
  name: falcon-three-7b
  labels:
    app.kubernetes.io/name: falcon-three-7b
    app.kubernetes.io/instance: falcon-three-7b
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 2080
      protocol: TCP
      name: falcon-three-7b
  selector:
    app.kubernetes.io/name: falcon-three-7b
    app.kubernetes.io/instance: falcon-three-7b