all:
  hosts:
    master:
      ansible_host: "{{ private_ip }}"
      ansible_user: ubuntu
      ansible_ssh_private_key_file: /path/to/your/ssh/key
    worker1:
      ansible_host: "{{ private_ip }}"
      ansible_user: ubuntu
      ansible_ssh_private_key_file: /path/to/your/ssh/key
    worker2:
      ansible_host: "{{ private_ip }}"
      ansible_user: ubuntu
      ansible_ssh_private_key_file: /path/to/your/ssh/key
  children:
    kube_control_plane:
      hosts:
        master:
    kube_node:
      hosts:
        worker1:
        worker2:
    etcd:
      hosts:
        master:
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
    calico_rr:
      hosts: {}