apiVersion: apps/v1
kind: Deployment
metadata:
  name: genai-gateway-deployment
  labels:
    app: litellm
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: litellm
  template:
    metadata:
      labels:
        app: litellm
    spec:
      initContainers:
        - name: wait-for-postgres-redis
          image: busybox:1.36
          command:
            - /bin/sh
            - -c
            - |
              until nc -z genai-gateway-postgresql.{{ .Release.Namespace }}.svc.cluster.local 5432 && nc -z genai-gateway-redis-master.{{ .Release.Namespace }}.svc.cluster.local 6379; do
                echo "Waiting for postgres and redis to be ready...";
                sleep 5;
              done
              echo "Postgres and Redis are up!"
{{- if .Values.restoreJob.enabled }}
        - name : wait-for-postgres-restore-job
          image: bitnami/kubectl:latest
          command:
            - /bin/sh
            - -c
            - |
              until kubectl get job postgres-restore -n {{ .Release.Namespace }}; do
                echo "Waiting for restore job to be created...";
                sleep 5;
              done
              echo "Restore job is created!"
{{- end }}
      containers:
        - name: litellm-container
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
{{- range $key, $value := .Values.env }}
            - name: {{ $key }}
              value: "{{ $value }}"
{{- end }}
          args:
            - "--config"
            - "/litellm/proxy_config.yaml"
          volumeMounts:
            - name: config-volume
              mountPath: /litellm
              readOnly: true            
          livenessProbe:
            httpGet:
              path: /health/liveliness
              port: {{ .Values.service.port }}
            initialDelaySeconds: 120
            periodSeconds: 15
            successThreshold: 1
            failureThreshold: 3
            timeoutSeconds: 10
          readinessProbe:
            httpGet:
              path: /health/readiness
              port: {{ .Values.service.port }}
            initialDelaySeconds: 120
            periodSeconds: 15
            successThreshold: 1
            failureThreshold: 3
            timeoutSeconds: 10
      volumes:
        - name: config-volume
          configMap:
            name: genai-gateway-config
        - name: on-prem-cert
          configMap:
            name: litellm-on-prem-cert