{{- if .Values.backup.enabled }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: genai-gateway-postgres-backup  
spec:
  schedule: "{{ .Values.backup.postgresBackupSchedule }}" 
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: pg-backup
            image: postgres:17.5
            env:         
            - name: PGURL
              value: "{{ .Values.env.DATABASE_URL }}"
            - name: AWS_ACCESS_KEY_ID
              value: "{{ .Values.backup.s3.accessKeyId }}"
            - name: AWS_SECRET_ACCESS_KEY
              value: "{{ .Values.backup.s3.secretAccessKey }}"
            - name: AWS_DEFAULT_REGION
              value: "{{ .Values.backup.s3.region }}"
            command:
              - "/bin/bash"
              - "-c"
              - |
                apt-get update && apt-get install -y awscli && \
                BACKUP_FILE=/backup/backup-$(date +%F-%H-%M).sql && \
                pg_dump $PGURL > $BACKUP_FILE && \
                if [ "{{ .Values.backup.uploadToS3 }}" = "true" ]; then \
                  aws s3 cp $BACKUP_FILE s3://{{ .Values.backup.s3.bucket }}/$(basename $BACKUP_FILE); \
                fi
            volumeMounts:
            - name: backup-volume
              mountPath: /backup
          restartPolicy: OnFailure
          volumes:
          - name: backup-volume
            persistentVolumeClaim:
              claimName: postgres-backup-pvc
{{- end }}