apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: genai-gateway-postgres-backup-pvc  
  annotations:
    "helm.sh/resource-policy": keep
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
