name: Coverity Scans

on:
  push:
    branches: [ main ]

jobs:
  coverity-scan:
    name: Coverity scans
    runs-on: [innersource.prod.amr.dind]
    container: cache-registry.caas.intel.com/cache/library/python:3.11
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Run Coverity scan for Python
      uses: ./.github/actions/coverity-scan
      with:
        ANALYZE_OPTIONS: --enable-default --security --webapp-security --enable-audit-checkers
        COMPILER_TYPE: python
        RAG_COVERITY_USER: ${{ secrets.RAG_COVERITY_USER }}
        RAG_COVERITY_PASSWORD: ${{ secrets.RAG_COVERITY_PASSWORD }}
